name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 1 # Add this to bust the cache if needed

      - name: Install Jekyll dependencies
        run: |
          cd "Admin Dashboard" # Change to the correct directory
          bundle install

      - name: Build Jekyll site
        run: |
          cd "Admin Dashboard" # Change to the correct directory again
          bundle exec jekyll build --source . --destination ../_site
        env:
          JEKYLL_ENV: production
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: /admin-dashboard
